version: "3"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-catalog-app
    ports:
      - "3001:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
    networks:
      - catalog-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: micro-catalog-elastic
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - ./.docker/elastic:/usr/share/elasticsearch/data
    networks:
      - catalog-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    ports:
      - "5601:5601"
    networks:
      - catalog-network

networks:
  catalog-network:
    driver: bridge
